spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf8&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.195
    port: 6379
server:
  context-path: "/sell"
wechat:
  mpAddId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  OpenAppId: xxxxxxxxxxxxxxxxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxxxxxxxx
  mchId: 1409146202
  mchkey: xxxxxxxxxxxxxxxxxxxxxxxx
  keyPath:  /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: xxxxxxxxxxxxxxxxxxx

projectUrl:
  wechatMpAuthorize: xxxx
  wechatOpenAuthorize: xxx
  sell: xxxxxx
logging:
  config:
    com.xc.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml